### ISSUE TITLE
It can't work in macOS Catalina. External Editor Not Open.

### ISSUE THREAD

**Issue by ghost** [libeanim/inkdrop-open-in-external-editor#3]
## Overview

It can't work in macOS Catalina, external editor not open.

* Plugin Installed
* Setting in Preferences 
* Restart Inkdrop
* Not open external editor

## Tryied (case: VSCode)

Settings

```
Editor path:
code

Editor arguments
--wait
```

## Tryied (case: Typora)

Settings

```
Editor path:
/Applications/Typora.app

Editor arguments
(Not set)
```

## Environment

Inkdrop v4.5.1
ProductName:	Mac OS X
ProductVersion:	10.15.2
BuildVersion:	19C57

**Comment by libeanim** [comment]
Ok, what is the output of the console, when you click on the "Open in external editor" button?

To see the output of the console, click "Toggle Developer Tools" in the menu under "Developer". A sidebar should appear. Select the tab "Console" at the top. Then click  on the "Open in external editor" button and copy the output.

**Comment by ghost** [comment]
> Ok, what is the output of the console, when you click on the "Open in external editor" button?
> 
> To see the output of the console, click "Toggle Developer Tools" in the menu under "Developer". A sidebar should appear. Select the tab "Console" at the top. Then click on the "Open in external editor" button and copy the output.

Thank you for your response.

As follows; 

in the case of VSCode
```
events.js:177 Uncaught Error: spawn code ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264)
    at onErrorNT (internal/child_process.js:456)
    at processTicksAndRejections (internal/process/task_queues.js:84)
errnoException @ internal/errors.js:463
ChildProcess._handle.onexit @ internal/child_process.js:264
onErrorNT @ internal/child_process.js:456
processTicksAndRejections @ internal/process/task_queues.js:84
```

in the case of Typora
```
events.js:177 Uncaught Error: spawn /Applications/Typora.app EACCES
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264)
    at onErrorNT (internal/child_process.js:456)
    at processTicksAndRejections (internal/process/task_queues.js:84)
errnoException @ internal/errors.js:463
ChildProcess._handle.onexit @ internal/child_process.js:264
onErrorNT @ internal/child_process.js:456
processTicksAndRejections @ internal/process/task_queues.js:84
```

**Comment by libeanim** [comment]
Ok thanks, so the first error often happens when the command does not exist.
When you run `code` in your system terminal, what happens, does it actually open VSCode?
Can you run `which code` and post it's output here.

For Typora, that is usually an error that occurs when the file is not marked as executable. Can you try to run `ls -l /Applications/Typora.app` from your terminal and post the output here. Additionally, can you also run `/Applications/Typora.app` and see if it opens.

**Comment by ghost** [comment]
Thank, you.
and I tried in Terminal.app

### case

```zsh
% code
```
result: open vscode app window with welcome page.

### case

```zsh
% ls -l /Applications/Typora.app
total 0
drwxr-xr-x  8 my_firstname.my_lastname  admin  256  1 11 16:41 Contents
```
 result: file exists.

### case

```zsh
% /Applications/Typora.app
% zsh: permission denied: /Applications/Typora.app
```
result: error

### case

```zsh
% open /Applications/Typora.app
```

result: open Typora app window.

**Comment by libeanim** [comment]
Ok thanks,

In the case of VSCode I'm not entirely sure why that fails, it seems inkdrop has a different `$PATH` environment variable.

Could you try to run `echo $PATH` in your terminal and `process.env.PATH` in the inkdrop developer console and then compare if there are any differences between the output?

EDIT: Regarding typora, your terminal does not seem to have permission to execute typora even though it is marked as executable on your file system (see the 3 `x`'s in your `ls` output). This confuses me a bit, I guess I would need to debug this manually. Maybe I can spin up a virtual machine with mac os to test it.

**Comment by ghost** [comment]
> Could you try to run echo $PATH in your terminal and process.env.PATH in the inkdrop developer 
> console and then compare if there are any differences between the output?

Inkdrop Developer Tools Output: 

```
process.env.PATH
"/usr/bin:/bin:/usr/sbin:/sbin"
```

```zsh
% which code
/usr/local/bin/code
```

Are there any good methods for that?
how to change process.env.PATH values.

**Comment by libeanim** [comment]
The simplest workaround would be to put `/usr/local/bin/code` into the `editor path` textbox of the plugin. (Instead of just `code`)

**Comment by Shigenori-Sagawa-nm** [comment]
> The simplest workaround would be to put /usr/local/bin/code into the editor path textbox of
> the plugin. (Instead of just code)

Solved!

Thank you for your quick and polite response. 😊

**Comment by libeanim** [comment]
Regarding Typora, I assume the problem might be that the app is not installed through the app store.
Maybe if you put `open /Applications/Typora.app` into the editor path it works.
